import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Use | UK Profit Calculator",
  description:
    "Read the Terms of Use for UK Profit Calculator, including service scope, liability limits, refunds, and governing law.",
  alternates: {
    canonical: "/terms",
  },
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gray-50">
      <div className="max-w-3xl mx-auto py-12 px-4 space-y-6 text-gray-800">
        <h1 className="text-3xl font-semibold text-gray-900">TERMS OF USE</h1>
        <p className="text-sm">(UK Profit Calculator – Version for Sole Trader SaaS)</p>
        <p className="text-sm">Last updated: January 2026</p>

        <p>Welcome to UK Profit Calculator (ukprofit.co.uk).</p>
        <p>By using this website, you agree to these Terms of Use.</p>
        <p>If you do not agree, please do not use this website.</p>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-gray-900">1. About This Website</h2>
          <p>UK Profit Calculator provides online financial estimation tools for UK-based businesses, self-employed individuals and e-commerce operators.</p>
          <p>All calculators and tools are provided for informational and educational purposes only.</p>
          <p>This website does not provide:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Financial advice</li>
            <li>Tax advice</li>
            <li>Legal advice</li>
            <li>Accounting services</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-gray-900">2. No Professional Advice</h2>
          <p>All results generated by our calculators are estimates based on the information entered by users.</p>
          <p>Nothing on this website constitutes regulated financial advice under UK law.</p>
          <p>We are not:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Regulated by the Financial Conduct Authority (FCA)</li>
            <li>Chartered Accountants</li>
            <li>Registered Tax Advisers</li>
            <li>Financial Planners</li>
          </ul>
          <p>You should consult a qualified UK accountant or tax adviser before making financial decisions.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-gray-900">3. Paid Questions / Digital Services</h2>
          <p>We may offer optional paid digital services such as written responses to business or tax-related questions.</p>
          <p>By purchasing such services, you agree that:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>The response provided is informational only</li>
            <li>It does not constitute regulated financial or tax advice</li>
            <li>It does not create a client–advisor relationship</li>
            <li>It does not replace professional consultation</li>
          </ul>
          <p>No liability is accepted for business, financial, or tax decisions made based on responses provided.</p>
          <p>All services are digital and delivered electronically.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-gray-900">4. User Responsibility</h2>
          <p>You remain fully responsible for:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Income Tax / Self Assessment filings</li>
            <li>VAT registration and submissions</li>
            <li>Corporation Tax (if applicable)</li>
            <li>National Insurance contributions</li>
            <li>Business compliance with HMRC</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-gray-900">5. Limitation of Liability</h2>
          <p>To the fullest extent permitted under UK law, UK Profit Calculator shall not be liable for:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Business losses</li>
            <li>Loss of profit</li>
            <li>Tax miscalculations</li>
            <li>Penalties imposed by HMRC</li>
            <li>Reliance on calculator outputs</li>
          </ul>
          <p>Nothing in these Terms excludes liability for:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Death or personal injury caused by negligence</li>
            <li>Fraud or fraudulent misrepresentation</li>
            <li>Any liability that cannot legally be excluded</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-gray-900">6. Intellectual Property</h2>
          <p>All website content, branding, design, tools and calculation logic remain the intellectual property of UK Profit Calculator.</p>
          <p>You may not copy, reproduce or redistribute any part of this website without permission.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-gray-900">7. Refund Policy (Digital Services)</h2>
          <p>As our paid services are digital and delivered electronically:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Once a response has been delivered, no refund is available.</li>
            <li>If no response has been delivered, you may request a refund within 14 days of purchase.</li>
          </ul>
          <p>This does not affect your statutory rights under UK consumer law.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-gray-900">8. Governing Law</h2>
          <p>These Terms are governed by the laws of England and Wales.</p>
          <p>Any disputes shall be subject to the jurisdiction of the courts of England and Wales.</p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-gray-900">9. Contact</h2>
          <p>For enquiries:</p>
          <p>Email: admin@ukprofit.co.uk</p>
        </section>
      </div>
    </main>
  );
}
